### ISSUE TITLE
Use %license

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/cpanspec#11]
I believe the generated spec's should use `%license` , similar to how https://github.com/openSUSE/py2pack/ works.

**Comment by coolo** [comment]
It does. It depends on the detection of license filenames though. But look e.g. at
https://build.opensuse.org/package/view_file/openSUSE:Factory/perl-Test-Inter/perl-Test-Inter.spec?expand=1

If it doesn't work on an example then because this function failed:
https://github.com/openSUSE/cpanspec/blob/master/cpanspec#L724

**Comment by jayvdb** [comment]
ok, ill retrace my steps to see which cases I encountered where it wasnt working.

As an aside, other differences with py2pack / spec-cleaner i've noticed

- they use `URL:` instead of `Url:`
- they remove the `BuildRoot:` ... it is unnecessary with modern rpmbuild?

**Comment by jayvdb** [comment]
`%license` didnt work on https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:perl/perl-Dist-Zilla-Plugin-Git

**Comment by coolo** [comment]
BuildRoot is not necessary, no. And about URL vs Url exists a long discussion on opensuse-packaging - it's a matter of taste.

**Comment by coolo** [comment]
Well, https://grammarist.com/spelling/licence-license/ :)

But that should be a quick fix

**Comment by jayvdb** [comment]
Fixed in https://github.com/openSUSE/cpanspec/commit/43afd0f463eb5c7375f948c6a99afe9ac086bb0d
